// Markdown report renderer (for pasting into issues / PRs / discussions).
import { T, fmtNum, fmtTopEn, fmtTopZh } from './terminal.js';
import { sanitize } from '../ansi.js';

// Pipe a cell's content so it can't break out of the table structure. Escape
// backslashes FIRST, or a literal "\|" survives as an escaped pipe and still
// splits the row. Also strip control/escape sequences from repo-controlled text.
const cell = (s) =>
  sanitize(s ?? '').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

export function renderMarkdown({ facts, scorecard, benchmark, locale, stale = false }) {
  const f = facts;
  const zh = locale === 'zh';
  const out = [];

  if (stale) {
    out.push(zh
      ? '> ⚠️ **数据非实时**：本次审计因限流使用了本地缓存数据生成，并非实时结果。'
      : '> ⚠️ **STALE DATA**: this audit was rate-limited and rendered from cached data — not a live result.');
    out.push('');
  }

  out.push(zh ? `# 🩺 ${f.fullName} 体检报告` : `# 🩺 ${f.fullName} scorecard`);
  out.push('');
  out.push(
    zh
      ? `**总分 ${scorecard.overall}/100（${scorecard.grade}）** · ★ ${fmtNum(f.stars)} · ${f.language ?? '?'}${f.isArchived ? ' · 已归档' : ''}${f.isFork ? ' · fork' : ''}`
      : `**Overall ${scorecard.overall}/100 (${scorecard.grade})** · ★ ${fmtNum(f.stars)} · ${f.language ?? '?'}${f.isArchived ? ' · archived' : ''}${f.isFork ? ' · fork' : ''}`
  );
  if (benchmark) {
    out.push(
      zh
        ? `**生态分位**：${fmtTopZh(benchmark)}（${f.language ?? 'GitHub'}）`
        : `**Ecosystem**: ${fmtTopEn(benchmark)} of ${f.language ?? 'GitHub'} repos`
    );
  }
  out.push('');
  out.push(zh ? '## 支柱得分' : '## Pillars');
  out.push('');
  out.push(zh ? '| 支柱 | 得分 | 权重 |' : '| Pillar | Score | Weight |');
  out.push('|---|---|---|');
  for (const p of scorecard.pillars) {
    if (p.score === null) continue;
    out.push(`| ${T(p.name, locale)} | ${p.score} | ${p.weight} |`);
  }
  out.push('');

  if (scorecard.quickWins.length) {
    out.push(zh ? '## ⚡ 最值得先做的三件事' : '## ⚡ Top fixes');
    out.push('');
    scorecard.quickWins.forEach((c, i) => {
      out.push(`${i + 1}. **${T(c.title, locale)}** \`${c.impact}\``);
      if (c.detail) out.push(`   - ${zh ? '证据' : 'Evidence'}: ${T(c.detail, locale)}`);
      if (c.fix) out.push(`   - ${zh ? '修复' : 'Fix'}: ${T(c.fix, locale)}`);
    });
    out.push('');
  }

  out.push(zh ? '## 全部检查项' : '## All checks');
  out.push('');
  out.push(zh ? '| 状态 | 检查项 | 证据 |' : '| Status | Check | Evidence |');
  out.push('|---|---|---|');
  for (const p of scorecard.pillars) {
    const mine = scorecard.allChecks.filter((c) => c.pillar === p.id);
    if (!mine.length) continue;
    out.push(`| | **${cell(T(p.name, locale))}** | |`);
    for (const c of mine) {
      const icon = { pass: '✅', warn: '⚠️', fail: '❌', skip: '➖' }[c.status];
      out.push(`| ${icon} | ${cell(T(c.title, locale))} | ${cell(T(c.detail, locale)) || '—'} |`);
    }
  }
  out.push('');
  out.push(
    zh
      ? '---\n*由 [why-no-stars](https://github.com/paopaonb666/why-no-stars) 生成 · star 不是玄学，是前 10 秒的功夫。*'
      : '---\n*Generated by [why-no-stars](https://github.com/paopaonb666/why-no-stars) · stars aren’t luck.*'
  );
  return out.join('\n');
}
