// Markdown report renderer (for pasting into issues / PRs / discussions).
import { T, fmtTopEn, fmtTopZh } from './terminal.js';

export function renderMarkdown({ facts, scorecard, benchmark, locale }) {
  const f = facts;
  const zh = locale === 'zh';
  const out = [];

  out.push(zh ? `# 🩺 ${f.fullName} 体检报告` : `# 🩺 ${f.fullName} scorecard`);
  out.push('');
  out.push(
    zh
      ? `**总分 ${scorecard.overall}/100（${scorecard.grade}）** · ★ ${f.stars} · ${f.language ?? '?'}`
      : `**Overall ${scorecard.overall}/100 (${scorecard.grade})** · ★ ${f.stars} · ${f.language ?? '?'}`
  );
  if (benchmark) {
    out.push(
      zh
        ? `**生态分位**：${fmtTopZh(benchmark)} 的 ${f.language ?? 'GitHub'} 仓库`
        : `**Star percentile**: ${fmtTopEn(benchmark)} of ${f.language ?? 'GitHub'} repos`
    );
  }
  out.push('');
  out.push(zh ? '## 支柱得分' : '## Pillars');
  out.push('');
  out.push(zh ? '| 支柱 | 得分 | 权重 |' : '| Pillar | Score | Weight |');
  out.push('|---|---|---|');
  for (const p of scorecard.pillars) {
    if (p.score === null) continue;
    out.push(`| ${T(p.name, locale)} | ${p.score} | ${p.weight} |`);
  }
  out.push('');

  if (scorecard.quickWins.length) {
    out.push(zh ? '## ⚡ 最值得先做的三件事' : '## ⚡ Top fixes');
    out.push('');
    scorecard.quickWins.forEach((c, i) => {
      out.push(`${i + 1}. **${T(c.title, locale)}** \`${c.impact}\``);
      if (c.detail) out.push(`   - ${zh ? '证据' : 'Evidence'}: ${T(c.detail, locale)}`);
      if (c.fix) out.push(`   - ${zh ? '修复' : 'Fix'}: ${T(c.fix, locale)}`);
    });
    out.push('');
  }

  out.push(zh ? '## 全部检查项' : '## All checks');
  out.push('');
  out.push(zh ? '| 状态 | 检查项 | 证据 |' : '| Status | Check | Evidence |');
  out.push('|---|---|---|');
  for (const p of scorecard.pillars) {
    for (const c of p.checks) {
      const icon = { pass: '✅', warn: '⚠️', fail: '❌', skip: '➖' }[c.status];
      out.push(`| ${icon} | ${T(c.title, locale)} | ${T(c.detail, locale) || '—'} |`);
    }
  }
  out.push('');
  out.push(
    zh
      ? '---\n*由 [why-no-stars](https://github.com/paopaonb666/why-no-stars) 生成 · star 不是玄学，是前 10 秒的功夫。*'
      : '---\n*Generated by [why-no-stars](https://github.com/paopaonb666/why-no-stars) · stars aren’t luck.*'
  );
  return out.join('\n');
}
